version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: urlshortener
      POSTGRES_DB: urlshortener
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    command: -p 5433

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: /api
    environment:
      DB_HOST: postgres
      DB_USER: urlshortener
      DB_PASSWORD: urlshortener
      DB_NAME: urlshortener
      DB_PORT: 5433
      JWT_SECRET: your-secret-key
      API_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - postgres

  redirect:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: /redirect
    environment:
      DB_HOST: postgres
      DB_USER: urlshortener
      DB_PASSWORD: urlshortener
      DB_NAME: urlshortener
      DB_PORT: 5433
      REDIRECT_PORT: 8083
    ports:
      - "8083:8083"
    depends_on:
      - postgres

volumes:
  postgres_data: 