FROM golang:1.23-alpine

WORKDIR /app

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Copy only the go.mod and go.sum first to leverage Docker cache
COPY go.mod ./
COPY go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Build the applications
RUN CGO_ENABLED=1 go build -o /api ./backend/cmd/api
RUN CGO_ENABLED=1 go build -o /redirect ./backend/cmd/redirect

EXPOSE 8080
EXPOSE 8081 